name: 更新qqread

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
  watch:
    types: [started]
  schedule:
    - cron: 0 6 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.SCRIPTS_PATH }}
        token: ${{ secrets.SCRIPTS_PAT }}
        ref: master
        path: ss

    - name: 获取原始仓库
      run: |
        cd ss
        rm -rf qqread || true
        rm -rf repo_qqread || true
        git clone https://github.com/Water008/qqread.git repo_qqread
        cd repo_qqread
        rm -rf .git
        cd ..
        rm -rf qqread_js || true
        rm -rf repo_qqread_js || true
        git clone https://github.com/ziye12/JavaScript.git repo_qqread_js
        cd repo_qqread_js
        rm -rf .git
        cd ..

        rm -rf repo_dailycheckin || true
        git clone https://github.com/Sitoi/dailycheckin.git repo_dailycheckin
        cd repo_dailycheckin
        rm -rf .git
        cd ..

        rm -rf repo_jd_seckill || true
        git clone --single-branch --branch master https://github.com/huanghyw/jd_seckill.git repo_jd_seckill
        cd repo_jd_seckill
        rm -rf .git
        cd ..

        cd ..

    - name: 提交
      run: |
        cd ss
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update qqread auto commit" || true
        git push origin master || true
