name: 喜马拉雅

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
#   schedule:
#    - cron: '*/30 * * * * '

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.SCRIPTS_PATH }}
        token: ${{ secrets.SCRIPTS_PAT }}
        ref: master

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
        pip3 install -r requirements.txt

    - name: 运行【喜马拉雅】
      run: |
        python3 xmly/xmly_spped.py
      env:
        XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须
        TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}} # tg通知token
        TG_USER_ID:  ${{secrets.TG_USER_ID}}    # tg通知id
